Repository ThePandaDevs/pibe-api, pull requests merged in 2022-08, with the labels that each got.

#15 add seeder for notifications
  src/main/java/mx/com/pandadevs/pibeapi/models/notifications/entities/Notification.java
  src/main/java/mx/com/pandadevs/pibeapi/models/notifications/services/NotificationService.java
  src/main/java/mx/com/pandadevs/pibeapi/utils/InitialDataBase.java
Labels: enhancement

#17 Change format date on all DTOs
  src/main/java/mx/com/pandadevs/pibeapi/models/certifications/dto/CertificationDto.java
  src/main/java/mx/com/pandadevs/pibeapi/models/courses/dto/CourseDto.java
  src/main/java/mx/com/pandadevs/pibeapi/models/profile/dto/ProfileDto.java
  src/main/java/mx/com/pandadevs/pibeapi/models/studies/dto/StudyDto.java
  src/main/java/mx/com/pandadevs/pibeapi/models/vacants/dto/VacantDto.java
  src/main/java/mx/com/pandadevs/pibeapi/models/work_experiences/dto/WorkExperienceDto.java
Labels: enhancement

#19 fix register method
  src/main/java/mx/com/pandadevs/pibeapi/models/auth/AuthService.java
  src/main/java/mx/com/pandadevs/pibeapi/models/users/UserRepository.java
Labels: bug

#21 Fix/logs
  src/main/java/mx/com/pandadevs/pibeapi/models/vacants/controller/UserVacantContoller.java
  src/main/java/mx/com/pandadevs/pibeapi/models/vacants/controller/VacantController.java
Labels: documentation

#22 fix minor bug
  src/main/java/mx/com/pandadevs/pibeapi/models/auth/AuthService.java
Labels: bug

#28 Fix/resume
  src/main/java/mx/com/pandadevs/pibeapi/models/aptitudes/AptitudeRepository.java
  src/main/java/mx/com/pandadevs/pibeapi/models/aptitudes/AptitudeService.java
  src/main/java/mx/com/pandadevs/pibeapi/models/aptitudes/AptitudesController.java
  src/main/java/mx/com/pandadevs/pibeapi/models/benefits/Benefit.java
  src/main/java/mx/com/pandadevs/pibeapi/models/benefits/BenefitService.java
  src/main/java/mx/com/pandadevs/pibeapi/models/modes/Mode.java
  src/main/java/mx/com/pandadevs/pibeapi/models/modes/ModeController.java
  src/main/java/mx/com/pandadevs/pibeapi/models/modes/ModeService.java
  src/main/java/mx/com/pandadevs/pibeapi/models/periods/Period.java
  src/main/java/mx/com/pandadevs/pibeapi/models/periods/PeriodService.java
  src/main/java/mx/com/pandadevs/pibeapi/models/processes/ProcessService.java
  src/main/java/mx/com/pandadevs/pibeapi/models/schedule/Schedule.java
  src/main/java/mx/com/pandadevs/pibeapi/models/schedule/ScheduleService.java
  src/main/java/mx/com/pandadevs/pibeapi/models/styles/StyleController.java
  src/main/java/mx/com/pandadevs/pibeapi/models/styles/StyleService.java
  src/main/java/mx/com/pandadevs/pibeapi/models/vacants/service/VacantService.java
  src/main/java/mx/com/pandadevs/pibeapi/security/LogJwtService.java
  src/main/java/mx/com/pandadevs/pibeapi/utils/enums/Action.java
Labels: bug

#31 fix: Resumes methods post/put
  src/main/java/mx/com/pandadevs/pibeapi/models/languages/repository/LanguageRepository.java
  src/main/java/mx/com/pandadevs/pibeapi/models/languages/repository/ResumeLanguageRepository.java
  src/main/java/mx/com/pandadevs/pibeapi/models/languages/services/LanguageService.java
  src/main/java/mx/com/pandadevs/pibeapi/models/languages/services/ResumeLanguageService.java
  src/main/java/mx/com/pandadevs/pibeapi/models/profile/ProfileRepository.java
  src/main/java/mx/com/pandadevs/pibeapi/models/profile/ProfileService.java
  src/main/java/mx/com/pandadevs/pibeapi/models/profile/mapper/ProfileMapper.java
  src/main/java/mx/com/pandadevs/pibeapi/models/resumes/ResumeRepository.java
  src/main/java/mx/com/pandadevs/pibeapi/models/resumes/ResumeService.java
  src/main/java/mx/com/pandadevs/pibeapi/models/users/UserRepository.java
  src/main/java/mx/com/pandadevs/pibeapi/models/users/controller/ResumeUserController.java
Labels: bug

#35 fix: active elements
  src/main/java/mx/com/pandadevs/pibeapi/models/aptitudes/Aptitude.java
  src/main/java/mx/com/pandadevs/pibeapi/models/aptitudes/AptitudeService.java
  src/main/java/mx/com/pandadevs/pibeapi/models/aptitudes/dto/AptitudeDto.java
  src/main/java/mx/com/pandadevs/pibeapi/models/aptitudes/mapper/AptitudeMapper.java
  src/main/java/mx/com/pandadevs/pibeapi/models/certifications/CertificationRepository.java
  src/main/java/mx/com/pandadevs/pibeapi/models/certifications/CertificationService.java
  src/main/java/mx/com/pandadevs/pibeapi/models/courses/CourseRepository.java
  src/main/java/mx/com/pandadevs/pibeapi/models/courses/CourseService.java
  src/main/java/mx/com/pandadevs/pibeapi/models/languages/repository/ResumeLanguageRepository.java
  src/main/java/mx/com/pandadevs/pibeapi/models/languages/services/ResumeLanguageService.java
  src/main/java/mx/com/pandadevs/pibeapi/models/resumes/ResumeService.java
  src/main/java/mx/com/pandadevs/pibeapi/models/studies/StudyRepository.java
  src/main/java/mx/com/pandadevs/pibeapi/models/studies/StudyService.java
  src/main/java/mx/com/pandadevs/pibeapi/models/studies/dto/StudyDto.java
  src/main/java/mx/com/pandadevs/pibeapi/models/studies/mapper/StudyMapper.java
  src/main/java/mx/com/pandadevs/pibeapi/models/users/controller/ResumeUserController.java
  src/main/java/mx/com/pandadevs/pibeapi/models/work_experiences/WorkExperienceRepository.java
  src/main/java/mx/com/pandadevs/pibeapi/models/work_experiences/WorkExperienceService.java
  src/main/java/mx/com/pandadevs/pibeapi/models/work_experiences/dto/WorkExperienceDto.java
  src/main/java/mx/com/pandadevs/pibeapi/models/work_experiences/mapper/WorkExperienceMapper.java
Labels: bug

#38 fix: change resume style
  src/main/java/mx/com/pandadevs/pibeapi/models/resumes/ResumeRepository.java
  src/main/java/mx/com/pandadevs/pibeapi/models/resumes/ResumeService.java
  src/main/java/mx/com/pandadevs/pibeapi/models/styles/StyleService.java
  src/main/java/mx/com/pandadevs/pibeapi/models/users/controller/ResumeUserController.java
Labels: bug
